name: CI (Main Branch)

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpython3-dev python3-pip

      - name: Install maturin
        run: pip install maturin

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run unit tests
        run: cargo test --all

      - name: Build Python bindings
        run: maturin build --release

      - name: Archive wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypher_guard_wheel
          path: target/wheels/*.whl
