[package]
name = "cypher_guard_python_bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "<=0.20.3", features = ["extension-module"] }
cypher-guard = {path = "../cypher_guard" }