/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function validateCypher(query: string, schemaJson: string): boolean
export declare function getValidationErrors(query: string, schemaJson: string): Array<string>
export declare function parseQuery(query: string): object
