name: Rust CI

on:
  push:
    branches: [ main, feat/validation-rewrite, feat/javascript-binding-pullforward ]
    paths:
      - 'rust/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [ main, feat/validation-rewrite, feat/javascript-binding-pullforward ]
    paths:
      - 'rust/cypher_guard/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'

jobs:
  test:
    name: Test Rust (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: cd rust/cypher_guard && cargo build --verbose

    - name: Run tests
      run: cd rust/cypher_guard && cargo test --verbose