name: Rust Format & Lint

on:
  push:
    branches: [ main, feat/validation-rewrite, feat/javascript-binding-pullforward ]
    paths:
      - 'rust/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust-format.yml'
  pull_request:
    branches: [ main, feat/validation-rewrite, feat/javascript-binding-pullforward ]
    paths:
      - 'rust/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust-format.yml'

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt

    - name: Check code formatting
      run: cargo fmt --all -- --check

  lint:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Lint with clippy
      run: cd rust/cypher_guard && cargo clippy -- -D warnings -A clippy::uninlined_format_args